name: build-on-push

on:
  push:
    branches-ignore:
      - main

jobs:
  build-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup-jdk
        uses: actions/setup-java@v5
        with:
          java-version: 17 # later version don't support a compile target of Java which is important for some users
          distribution: 'temurin'
          cache: maven

      - name: maven-build-verify
        run: mvn --batch-mode --update-snapshots verify
