name: dependabot-pr-auto-merge

on:
  pull_request:
    branches:
      - dev
jobs:
  dependabot-pr-auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: dependabot-pr-fetch-metadata
        uses: dependabot/fetch-metadata@v2

      - name: dependabot-pr-approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: dependabot-pr-auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}